export const FEATURE_SAVE_KEY = "navigated_features_v1";

export const GAME_CONFIG = Object.freeze({
  combo: {
    max: 99,
    scoreMultipliers: Object.freeze({
      1: 1,
      2: 1.1,
      3: 1.2,
      5: 1.5,
      10: 1.5,
    }),
    coinStep: 0.03,
    maxCoinBonus: 0.2,
  },
  events: {
    chancePerSecond: 0.018,
    minLevel: 2,
    cooldownSeconds: 8,
    maxDurationSeconds: 7,
  },
  rewards: {
    comboMaxCoinBonus: 0.2,
    goldRushMultiplier: 1.25,
    dailyParticipationCoins: 25,
    dailyParticipationXp: 20,
    dailyTargetCoins: 75,
    dailyTargetXp: 60,
    weeklyParticipationCoins: 100,
    weeklyParticipationXp: 100,
  },
});

export const CORE_DEFS = Object.freeze([
  {
    id: "speed",
    name: "SPEED CORE",
    icon: "S",
    description: "일반 게임의 흐름을 조금 더 빠르게 만듭니다.",
    rarity: "COMMON",
    effect: "speed",
    levels: [0.03, 0.05, 0.08],
  },
  {
    id: "precision",
    name: "PRECISION CORE",
    icon: "P",
    description: "정확한 탈출에 작은 추가 보너스를 제공합니다.",
    rarity: "RARE",
    effect: "precision",
    levels: [0.04, 0.07, 0.1],
  },
  {
    id: "gold",
    name: "GOLD CORE",
    icon: "G",
    description: "일반 게임에서 코인 획득량을 높입니다.",
    rarity: "RARE",
    effect: "coin",
    levels: [0.05, 0.08, 0.12],
  },
  {
    id: "life",
    name: "LIFE CORE",
    icon: "L",
    description: "일반 모드에서 한 번의 실수를 완충합니다.",
    rarity: "EPIC",
    effect: "life",
    levels: [1, 1, 1],
  },
  {
    id: "combo",
    name: "COMBO CORE",
    icon: "C",
    description: "콤보 보너스가 조금 더 오래 유지됩니다.",
    rarity: "EPIC",
    effect: "combo",
    levels: [0.12, 0.2, 0.3],
  },
  {
    id: "luck",
    name: "LUCK CORE",
    icon: "U",
    description: "추가 보상과 코어 발견 확률을 높입니다.",
    rarity: "LEGENDARY",
    effect: "luck",
    levels: [0.03, 0.06, 0.1],
  },
]);

export const WORLD_DEFS = Object.freeze([
  {
    id: "forest",
    name: "WORLD 1",
    subtitle: "FOREST",
    theme: "forest",
    unlockAt: 0,
    nodes: ["1-1", "1-2", "1-3", "1-4", "BOSS"],
  },
  {
    id: "neon-city",
    name: "WORLD 2",
    subtitle: "NEON CITY",
    theme: "neon",
    unlockAt: 4,
    nodes: ["2-1", "2-2", "2-3", "2-4", "BOSS"],
  },
  {
    id: "space-station",
    name: "WORLD 3",
    subtitle: "SPACE STATION",
    theme: "space",
    unlockAt: 9,
    nodes: ["3-1", "3-2", "3-3", "3-4", "BOSS"],
  },
]);

export const EVENT_DEFS = Object.freeze([
  {
    id: "wind",
    label: "WIND",
    subtitle: "DIRECTION SHIFT",
    color: "#65d9ff",
    duration: 5,
    gameplay: "wind",
  },
  {
    id: "blackout",
    label: "BLACKOUT",
    subtitle: "VISION LIMITED",
    color: "#9b8cff",
    duration: 4,
    gameplay: "blackout",
  },
  {
    id: "overdrive",
    label: "OVERDRIVE",
    subtitle: "SPEED UP",
    color: "#ff639f",
    duration: 5,
    gameplay: "overdrive",
  },
  {
    id: "freeze",
    label: "FREEZE",
    subtitle: "BRIEF PAUSE",
    color: "#a6f1ff",
    duration: 2.5,
    gameplay: "freeze",
  },
  {
    id: "explosion",
    label: "EXPLOSION",
    subtitle: "OBSTACLE CLEAR",
    color: "#ffb454",
    duration: 1.5,
    gameplay: "explosion",
  },
  {
    id: "mirage",
    label: "MIRAGE",
    subtitle: "FALSE SIGNAL",
    color: "#ff88e8",
    duration: 4,
    gameplay: "mirage",
  },
  {
    id: "gold-rush",
    label: "GOLD RUSH",
    subtitle: "COINS BOOSTED",
    color: "#ffd45c",
    duration: 6,
    gameplay: "goldRush",
  },
]);
